name: Build and test back-end

on:
  push:
    branches:
      - main
    paths:
      - 'back-end/**'
      - '!**/README.md'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main      

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.x"

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test
