name: Build and deploy package

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.x"

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test
